<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="AxwayB2BiServAdmin" lastModifiedBy="imhurduc" checksumTest="true" creationDate="10/05/2016 21:01:58 +0300" engineType="DML" lastModifiedDate="28/08/2017 09:56:55 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/bdoc1.dmlflw"/>
   </mappingInformations>
</project>